### ISSUE TITLE
CTA link does not work

### ISSUE THREAD

**Issue by mnosrati** [projectestac/wordpress-pods#2]
href is not filled with the value that is set for CTA link for the red button on the cards. See the picture below:

![image](https://github.com/projectestac/wordpress-pods/assets/37707329/d6a6bc19-e59b-4988-87cf-451e5d552628)

**Comment by toniginard** [comment]
Hi, @mnosrati,

I really don't know what are you referring to, but, anyway, we are not the maintainers of this plugin. This is just a repository where we have a copy of the code for our convenience.

For any support questions, please, contact the maintainers through the official plugin page: https://wordpress.org/plugins/pods/


Best wishes,
Toni Ginard
